---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  path: ./apps/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-primer
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: flux-system
spec:
  path: ./apps/cert-manager/issuers
  prune: true
  dependsOn:
    - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-primer
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
