---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: nginx
spec:
  path: ./apps/nginx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-primer
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
