---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cdk-cats
  namespace: flux-system
spec:
  path: ./apps/cdk-cats/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-primer
  dependsOn:
    - name: cert-manager
    - name: ingress-nginx
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
